use std::{env, fmt::Write as _, fs, path::PathBuf};

// ---- layout.json (UI data) ------------------------------------------------

#[derive(serde::Deserialize)]
struct P2 {
    x: i32,
    y: i32,
}
#[derive(serde::Deserialize)]
struct Y1 {
    y: i32,
}
#[derive(serde::Deserialize)]
struct Bar {
    x: i32,
    w: u32,
    h: u32,
}
#[derive(serde::Deserialize)]
struct Layout {
    band_h: u32,
    title: P2,
    week: Y1,
    bar1: Y1,
    reset1: P2,
    win: Y1,
    bar2: Y1,
    reset2: P2,
    text_left: i32,
    text_right: i32,
    bar: Bar,
}

fn emit_layout(path: &std::path::Path) {
    println!("cargo:rerun-if-changed={}", path.display());
    let text = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("cannot read {}: {e}", path.display())
    });
    let l: Layout = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("{}: invalid layout JSON: {e}", path.display()));

    // Sanity checks (ranges mirror tools/layout-editor.html).
    let mut bad: Vec<String> = vec![];
    if !(12..=60).contains(&l.band_h) {
        bad.push("band_h must be 12..=60".into());
    }
    if l.title.x < 0 || l.title.x > 200 - 15 * 9 {
        bad.push("title.x out of range".into());
    }
    if l.title.y < 0 || l.title.y + 15 > l.band_h as i32 {
        bad.push("title.y must keep the title inside the header band".into());
    }
    // reset text is "reset MM-DD HH:mm" (17 chars), rendered 9px per char.
    if l.reset1.x < 0 || l.reset1.x > 200 - 17 * 9 {
        bad.push("reset1.x out of range".into());
    }
    if l.reset2.x < 0 || l.reset2.x > 200 - 17 * 9 {
        bad.push("reset2.x out of range".into());
    }
    if l.text_left < 0 || l.text_left > 180 {
        bad.push("text_left out of range".into());
    }
    if !(40..=199).contains(&l.text_right) {
        bad.push("text_right out of range".into());
    }
    if l.bar.x < 0 || l.bar.w < 20 || l.bar.x as u32 + l.bar.w > 200 || !(4..=60).contains(&l.bar.h) {
        bad.push("bar geometry out of range".into());
    }
    for (name, y) in [("week", l.week.y), ("reset1", l.reset1.y), ("win", l.win.y), ("reset2", l.reset2.y)] {
        if y < l.band_h as i32 + 1 || y > 184 {
            bad.push(format!("{name}.y out of range"));
        }
    }
    for (name, y) in [("bar1", l.bar1.y), ("bar2", l.bar2.y)] {
        if y < l.band_h as i32 + 1 || y > 200 - l.bar.h as i32 - 1 {
            bad.push(format!("{name}.y out of range"));
        }
    }
    if !bad.is_empty() {
        panic!("{}: invalid layout: {}", path.display(), bad.join("; "));
    }

    let mut code = String::from(
        "// Auto-generated by build.rs from firmware/layout.json — do not edit.\n",
    );
    writeln!(code, "pub const BAND_H: u32 = {};", l.band_h).unwrap();
    writeln!(code, "pub const TITLE_X: i32 = {};", l.title.x).unwrap();
    writeln!(code, "pub const TITLE_Y: i32 = {};", l.title.y).unwrap();
    writeln!(code, "pub const WEEK_Y: i32 = {};", l.week.y).unwrap();
    writeln!(code, "pub const BAR1_Y: i32 = {};", l.bar1.y).unwrap();
    writeln!(code, "pub const RESET1_X: i32 = {};", l.reset1.x).unwrap();
    writeln!(code, "pub const RESET1_Y: i32 = {};", l.reset1.y).unwrap();
    writeln!(code, "pub const WIN_Y: i32 = {};", l.win.y).unwrap();
    writeln!(code, "pub const BAR2_Y: i32 = {};", l.bar2.y).unwrap();
    writeln!(code, "pub const RESET2_X: i32 = {};", l.reset2.x).unwrap();
    writeln!(code, "pub const RESET2_Y: i32 = {};", l.reset2.y).unwrap();
    writeln!(code, "pub const TEXT_LEFT: i32 = {};", l.text_left).unwrap();
    writeln!(code, "pub const TEXT_RIGHT: i32 = {};", l.text_right).unwrap();
    writeln!(code, "pub const BAR_X: i32 = {};", l.bar.x).unwrap();
    writeln!(code, "pub const BAR_W: u32 = {};", l.bar.w).unwrap();
    writeln!(code, "pub const BAR_H: u32 = {};", l.bar.h).unwrap();

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("layout.rs");
    fs::write(&out, code).unwrap();
}

fn main() {
    println!("cargo:rustc-link-arg-bins=-Tlinkall.x");

    // Secrets (Wi-Fi credentials, API key) live in the gitignored `.env` at
    // the repo root (KEY=VALUE lines; see .env.example) and are baked into
    // the binary at compile time via cargo:rustc-env + env!().
    let dotenv = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("../.env");
    println!("cargo:rerun-if-changed={}", dotenv.display());
    let text = fs::read_to_string(&dotenv).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\ncopy .env.example to .env and fill it in",
            dotenv.display()
        )
    });
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            panic!("{}:{}: expected KEY=VALUE", dotenv.display(), lineno + 1);
        };
        let value = value.trim().trim_matches(|c| c == '"' || c == '\'');
        println!("cargo:rustc-env={}={}", key.trim(), value);
    }

    // Screen layout data (see tools/layout-editor.html) -> OUT_DIR/layout.rs,
    // pulled in by src/render.rs via include!().
    let layout = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("layout.json");
    emit_layout(&layout);
}
